schema {
    query: Query
}

#Query root
type Query {
    hero: Character
    droid(id: ID!): Droid
}

interface Character {
    id: ID!
    name: String!
    friends: [Character]
}

type Human implements Character {
    id: ID!
    name: String!
    friends: [Character]
    totalCredits: int
}

type Droid implements Character {
    id: ID!
    name: String!
    friends: [Character]
    primaryFunction: String
}