schema {
    query: Query
    mutation: Mutation
}

#Query root
type Query {
    hero: Character
    droid(id: ID!): Droid
    humans: [Human]
    object: Thing
}

type Mutation {
    doThing: Thing
}

input InputThing {
    number: Int
}

type Thing {
    field: String
    number: Int
}

interface Character {
    id: ID!
    name: String!
    friends: [Character]
}

type Human implements Character {
    id: ID!
    name: String!
    friends: [Character]
    totalCredits: int
}

type Droid implements Character {
    id: ID!
    name: String!
    friends: [Character]
    primaryFunction: String
}

enum Numbers {
    ONE
    TWO
    THREE
}

union Union = Human | Droid